version: '3'
services:
  app:   
    image: php:7.4-fpm
    volumes:
      - ./app:/var/www/html
    networks:
      - app-network
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: abccompany
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
  db_test:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: abccompany_test
    volumes:
      - db_data_test:/var/lib/mysql
    networks:
      - app-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
      - db_test
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    networks:
      - app-network
  nginx:
    image: nginx:latest
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/html
    ports:
      - 8001:80
    depends_on: 
      - app
    networks:
      - app-network
volumes:
  db_data:
  db_data_test:
networks:
  app-network:
    driver: bridge